#define ALICANTE                0
#define BARCELONA               1
#define BORDEAUX                2
#define CADIZ                   3
#define GRANADA                 4
#define LISBON                  5
#define MADRID                  6
#define SANTANDER               7
#define SARAGOSSA               8
#define TOULOUSE                9
#define ATLANTIC_OCEAN          10
#define BAY_OF_BISCAY           11
#define MEDITERRANEAN_SEA       12
#define UNKNOWN_LOCATION        -1
#define NUM_MAP_LOCATIONS       13
